In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)

In [10]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [11]:
a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [12]:
a = np.array([1, 2, 3], dtype=complex)
print(a)
print(type(a))

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


In [13]:
dt = np.dtype(np.int32)
print(dt)

int32


In [14]:
# first create structured data type
dt = np.dtype([('age', np.int8)])

# now apply it to ndarray object
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [15]:
# file name can be used to access content of age column
print(a['age'])

[10 20 30]


In [16]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [18]:
# this resizes the ndarray
a.shape = (3, 2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# NumPy also provides a reshape function to resize an array.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
# dtype of array is int8 (1 byte)
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(x.itemsize)

1


In [22]:
# dtype of array is now float32 (4 bytes)
x = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(x.itemsize)

4


In [23]:
# The following example shows the current values of flags:
x = np.array([1, 2, 3, 4, 5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [24]:
# The following code shows an example of an empty array:
x = np.empty([3, 2], dtype=int)
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
# array of five zeros. Default dtype is float:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [26]:
x = np.zeros((5), dtype=int)
print(x)

[0 0 0 0 0]


In [27]:
# custom type
x = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [28]:
# array of five ones. Default dtype is float:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [29]:
x = np.ones((5), dtype=int)
print(x)

[1 1 1 1 1]


In [30]:
x = np.ones([2, 2], dtype=int)
print(x)

[[1 1]
 [1 1]]


In [31]:
# convert list to ndarray:
x = [1, 2, 3]
a = np.asarray(x)
print(type(x))
print(a)

<class 'list'>
[1 2 3]


In [32]:
a = np.asarray(x, dtype=float)
print(a)

[1. 2. 3.]


In [33]:
# ndarray from tuple:
x = (1, 2, 3)
a = np.asarray(x)
print(a)

[1 2 3]


In [34]:
# ndarray from list of tuples:
x = [(1, 2, 3), (4, 5)]
a = np.asarray(x, dtype=list)
print(a)

[(1, 2, 3) (4, 5)]


In [35]:
# create list object using range function:
list = range(5)
list

range(0, 5)

In [36]:
# obtain iterator object from list:
list = range(5)
it = iter(list)
x = np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [37]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [38]:
# dtype set
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [39]:
# start and stop parameters set
x = np.arange(10, 20, 2)
print(x)

[10 12 14 16 18]


In [40]:
# numpy.linspace
# This function is similar to arange() function.
# In this function, instead of step size, the number of evenly spaced values
# between the interval is specified.
x = np.linspace(10, 20, 5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [41]:
# endpoint set to false:
x = np.linspace(10, 20, 5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [42]:
# find retstep value
x = np.linspace(1, 2, 5, retstep=True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [43]:
# numpy.logspace
# This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. 
# Start and stop endpoints of the scale are indices of the base, usually 10.
a = np.logspace(1.0, 2.0, num=10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [44]:
a = np.logspace(1, 10, num=10, base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [50]:
# INDEXING AND SLICING
a = np.arange(10)
s = slice(2, 7, 2)
print(a[s])

[2 4 6]


In [51]:
# The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.
b = a[2:7:2]
print(b)

[2 4 6]


In [53]:
# The above description applies to multi-dimensional ndarray too.
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [54]:
# this returns array of items in the second column
print(a[...,1])

[2 4 5]


In [55]:
# Now we will slice all items from the second row
print(a[1,...])

[3 4 5]


In [56]:
# Now we will slice all items from column 1 onwards
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


In [57]:
# ADVANCED INDEXING
# Integer Indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
# y = x[[row indexes], [column indexes]]
print(y)

[1 4 5]


In [59]:
# In the following example, elements placed at corners of a 4X3 array are selected.
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [60]:
rows = np.array([[0, 0], [3, 3]])
columns = np.array([[0, 2], [0, 2]])
y = x[rows, columns]
print(y)

[[ 0  2]
 [ 9 11]]


In [64]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
# Slicing
print(x[1:4, 1:3])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [63]:
# Slicing using advanced index for column
print(x[1:4, [1, 2]])

[[ 4  5]
 [ 7  8]
 [10 11]]


In [65]:
# BOOLEAN ARRAY INDEXING
# Now we will print the items greater than 5
print(x[x > 5])

[ 6  7  8  9 10 11]


In [69]:
# In this example, NaN (Not a Number) elements are omitted by using ~ (complement operator)
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [70]:
# The following example shows how to filter out the non-complex elements from an array.
a = np.array([1, 2+6j, 5, 3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [72]:
# BROADCASTING
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a * b
print(c)

[ 10  40  90 160]


In [74]:
# Example of broadcasting with arrays with different ndim
a = np.array([[0.0, 0.0, 0.0], [10.0, 10.0, 10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
print(a + b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [76]:
# ITERATING OVER ARRAYS
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [91]:
# A modified array is:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [78]:
# Transpose of the original array is:
b = a.T
print(b)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [79]:
for x in np.nditer(b):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [88]:
# If the same elements are stored using F-style order, the iterator chooses the more efficient way of iterating over an array.
# Sorted in C-style order:
c = b.copy(order="C")
print(c)
for x in np.nditer(c):
    print(x)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


In [89]:
# Sorted in F-style order:
c = b.copy(order="F")
print(c)
for x in np.nditer(c):
    print(x)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [94]:
# It is possible to force nditer object to use a specific order by explicitly mentioning it.
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("Sorted in C-style order:")
for x in np.nditer(a, order="C"):
    print(x)

print("\n")
print("Sorted in F-style order:")
for x in np.nditer(a, order="F"):
    print(x)

Sorted in C-style order:
0
5
10
15
20
25
30
35
40
45
50
55


Sorted in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


MODIFYING ARRAY VALUES

In [98]:
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("The original array is:")
print(a)
for x in np.nditer(a, op_flags=["readwrite"]):
    x[...] = 2*x
print("\nThe modified array is:")
print(a)

The original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

The modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [102]:
# External Loop
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print("The original array is:")
print(a)
print("\nThe modified array is:")
for x in np.nditer(a, flags=["external_loop"], order="F"):
    print(x,)

The original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

The modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


MATRIX ARITHMETIC OPERATIONS

In [18]:
a = np.arange(9, dtype=float).reshape(3, 3)
print("First array")
print(a)
b = np.array([10, 10, 10])
print("\nSecond array")
print(b)

First array
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

Second array
[10 10 10]


In [19]:
adition = np.add(a, b)
adition

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [20]:
subtraction = np.subtract(a, b)
subtraction

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [21]:
multip = np.multiply(a, b)
multip

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

In [22]:
division = np.divide(a, b)
division

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [24]:
# Reciprocal of an array
a = np.array([0.25, 1.33, 1, 0, 100])
np.reciprocal(a)

C:\Users\acaic\AppData\Local\Temp\ipykernel_3160\696522007.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal(a)


array([4.       , 0.7518797, 1.       ,       inf, 0.01     ])

In [25]:
b = np.array([100], dtype=int)
np.reciprocal(b)

array([0])

In [26]:
# Power of an array
a = np.array([10, 100, 1000])
np.power(a, 2)

array([    100,   10000, 1000000], dtype=int32)

In [27]:
b = np.array([1, 2, 3])
np.power(a, b)

array([        10,      10000, 1000000000])

In [29]:
# Remainder of an array
a = np.array([10, 20, 30])
b = np.array([3, 5, 7])
print(np.mod(a, b))
print(np.remainder(a, b))

[1 0 2]
[1 0 2]


Functions with complex numbers

In [30]:
a = np.array([-5.6j, 0.2j, 11., 1+1j])
np.real(a)

array([-0.,  0., 11.,  1.])

In [31]:
np.imag(a)

array([-5.6,  0.2,  0. ,  1. ])

In [32]:
np.conj(a)

array([-0.+5.6j,  0.-0.2j, 11.-0.j ,  1.-1.j ])

In [33]:
# In radians
np.angle(a)

array([-1.57079633,  1.57079633,  0.        ,  0.78539816])

In [34]:
# In degrees
np.angle(a, deg=True)

array([-90.,  90.,   0.,  45.])

STATISTICAL FUNCTIONS

In [41]:
a = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

Max and Min

In [48]:
np.amin(a, 1)

array([3, 3, 2])

In [49]:
np.amin(a, 0)

array([2, 4, 3])

In [44]:
np.amax(a)

9

In [45]:
np.amax(a, axis=0)

array([8, 7, 9])

In [46]:
# returns the range (maximum-minimum) of values along an axis
# If no axis is specify, return the range (max - min) of the whole array.
np.ptp(a)

7

In [47]:
np.ptp(a, axis=1)

array([4, 5, 7])

In [50]:
np.ptp(a, axis=0)

array([6, 3, 6])

In [51]:
a = np.array([[30, 40, 70], [80, 20, 10], [50, 90, 60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

Percentile

In [52]:
# numpy.percentile(array, percentile, axis)
np.percentile(a, 50)

50.0

In [53]:
np.percentile(a, 50, axis=1)

array([40., 20., 60.])

In [54]:
np.percentile(a, 50, axis=0)

array([50., 40., 60.])

In [55]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

Mean and Weighted Average

In [56]:
np.mean(a)

3.6666666666666665

In [57]:
np.mean(a, axis=0)

array([2.66666667, 3.66666667, 4.66666667])

In [58]:
np.mean(a, axis=1)

array([2., 4., 5.])

In [59]:
a = np.array([1, 2, 3, 4])
np.average(a)

2.5

In [60]:
# Weighted average
wts = np.array([4, 3, 2, 1])
np.average(a, weights=wts)

2.0

In [61]:
# Sum of weights
np.average(a, weights=wts, returned=True)

(2.0, 10.0)

In [63]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [64]:
wts = np.array([3, 5])
np.average(a, axis=1, weights=wts)

array([0.625, 2.625, 4.625])

In [65]:
  np.average(a, axis=1, weights=wts, returned=True)

(array([0.625, 2.625, 4.625]), array([8., 8., 8.]))

Standard Deviation

In [66]:
np.std([1, 2, 3, 4])

1.118033988749895

Variance

In [67]:
np.var([1, 2, 3, 4])

1.25

AttributeError: module 'numpy' has no attribute 'rd'